SET NAMES ujis;
update c_review_category set category='Books' where c_review_category_id=1;
update c_review_category set category='ForeignBooks' where c_review_category_id=2;
update c_review_category set category='Electronics' where c_review_category_id=3;
update c_review_category set category='Kitchen' where c_review_category_id=4;
update c_review_category set category='Music' where c_review_category_id=5;
update c_review_category set category='DVD' where c_review_category_id=6;
update c_review_category set category='Software' where c_review_category_id=7;
update c_review_category set category='VideoGames' where c_review_category_id=8;
update c_review_category set category='Toys' where c_review_category_id=9;
