types:
  3gp: video/3gpp
  3g2: video/3gpp2
  aac: audio/x-aac
  aif: audio/x-aiff
  aifc: audio/x-aiff
  aiff: audio/x-aiff
  css: text/css
  csv: text/csv
  dat: application/octet-stream
  dmt: application/x-decomail-template
  doc: application/vnd.ms-word
  docx: application/vnd.openxmlformats-officedocument.wordprocessingml.document
  eml: message/rfc822
  eps: application/postscript
  flv: video/x-flv
  gif: image/gif
  gz: application/x-gzip
  h264: video/quicktime
  haml: text/x-haml
  hmt: application/x-htmlmail-template
  htm: text/html
  html: text/html
  ico: image/x-ico
  ini: text/x-ini-file
  jpg: image/jpeg
  jpeg: image/jpeg
  js: text/javascript
  json: application/json
  khm: application/x-kddi-htmlmail
  m4a: audio/mp4
  mime: message/rfc822
  mov: video/quicktime
  mp3: audio/mpeg
  mp4: video/mp4
  mp4a: audio/mp4
  mpeg: video/mpeg
  mpg: video/mpeg
  odp: application/vnd.oasis.opendocument.presentation
  ods: application/vnd.oasis.opendocument.spreadsheet
  odt: application/vnd.oasis.opendocument.text
  pdf: application/pdf
  png: image/png
  ppt: application/vnd.ms-powerpoint
  pptx: application/vnd.openxmlformats-officedocument.presentationml.presentation
  qt: video/quicktime
  rb: text/ruby
  ru: text/ruby
  sass: text/x-sass
  swf: application/x-shockwave-flash
  tgz: application/x-gzip
  tif: image/tiff
  tiff: image/tiff
  tpl: text/x-smarty-template
  ttf: application/x-truetype-font
  txt: text/plain
  wma: audio/x-ms-wma
  wav: audio/x-wav
  wmv: video/x-ms-wmv
  yaml: text/yaml
  yml: text/yaml
  xhtml: application/xhtml+xml
  xls: application/vnd.ms-excel
  xlsx: application/vnd.openxmlformats-officedocument.wordprocessingml.document
  xml: application/xml
  vcf: text/x-vcard
  zip: application/zip

